# cmd - snow --config-file=config.toml connection test -c snowsarva

[connections.snowsarva]
account = "YECALEZ-TCB02565"
user = "snowsarva_user"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token_file_path = "snowflake-pat.token"
role = "SNOWSARVA_ROLE"
warehouse = "SNOWSARVA_WAREHOUSE"
database = "SNOWSARVA_IMAGE_DATABASE"
schema = "SNOWSARVA_IMAGE_SCHEMA"