# cmd - snow --config-file="config.toml" connection test -c test

[connections.snowsarva]
account = "CHFWNRV-DDB48976"
user = "snowsarva_user"
authenticator = "PROGRAMMATIC_ACCESS_TOKEN"
token_file_path = "snowflake-pat.token"
role = "snowsarva_role"
warehouse = "snowsarva_warehouse"
database = "snowsarva_image_database"
schema = "snowsarva_image_schema"